"""Hosted Arena Agent runtime.

The production decision path uses a bounded PydanticAI Agent while preserving
the durable Arena AgentTask/Result, Secret Store, Attempt, and Result Sink
boundaries.
"""

from .attempts import (
    AttemptCompletion,
    AttemptCreated,
    AttemptRecord,
    AttemptRecorder,
    MemoryAttemptRecorder,
)
from .capabilities import (
    CAPABILITY_SCHEMA_VERSION_V1,
    DEFAULT_REGISTRY_VERSION_V1,
    CapabilityError,
    CapabilityRegistry,
    ModelCapability,
    PublicModelCapability,
    ResolvedModelCapability,
    ThinkingEffortPolicy,
    ThinkingMode,
)
from .context import HostedArenaAgentContext
from .memory import (
    GameMemoryPatch,
    HostedAgentRunOutput,
    HostedGameMemory,
    SafeDecisionSummary,
)
from .model_factory import BuiltPydanticModel, PydanticModelFactory
from .providers import (
    FakeProvider,
    FakeProviderScenario,
    FakeProviderStep,
    ProviderAdapter,
    ProviderInvocationError,
    ProviderRequest,
    ProviderResponse,
    ProviderUsage,
)
from .secret_store import (
    DeploymentEnvironment,
    MemorySecretStore,
    SecretBackend,
    SecretController,
    SecretReader,
    SecretReference,
    SecretStoreConfigurationError,
    SecretStoreError,
    SecretStoreOperationError,
    SecretStorePorts,
    SecretStoreSettings,
    SecretWrite,
    SecretWriter,
    TencentSecretController,
    TencentSecretReader,
    TencentSecretWriter,
    TencentSsmSettings,
    WorkerSecret,
    build_secret_store_ports,
    tencent_sdk_is_importable,
)
from .runtime import (
    HostedAgentExecution,
    HostedAgentRuntimeLimits,
    HostedArenaAgentRuntime,
)
from .runtime_contract import (
    AGENT_ACTION_SCHEMA_VERSION_V1,
    HOSTED_AGENT_INSTRUCTION_VERSION_V1,
    MAX_STRATEGY_BYTES,
)
from .strategy import (
    STRATEGY_CATALOG_VERSION_V1,
    StrategyArchetype,
    StrategyPreset,
    official_strategy_archetype,
    render_strategy_revision,
    strategy_preset,
)

__all__ = [
    "CAPABILITY_SCHEMA_VERSION_V1",
    "DEFAULT_REGISTRY_VERSION_V1",
    "AttemptCompletion",
    "AttemptCreated",
    "AttemptRecord",
    "AttemptRecorder",
    "AGENT_ACTION_SCHEMA_VERSION_V1",
    "BuiltPydanticModel",
    "CapabilityError",
    "CapabilityRegistry",
    "DeploymentEnvironment",
    "FakeProvider",
    "FakeProviderScenario",
    "FakeProviderStep",
    "GameMemoryPatch",
    "HostedAgentExecution",
    "HostedAgentRunOutput",
    "HostedAgentRuntimeLimits",
    "HostedArenaAgentContext",
    "HostedArenaAgentRuntime",
    "HostedGameMemory",
    "HOSTED_AGENT_INSTRUCTION_VERSION_V1",
    "MAX_STRATEGY_BYTES",
    "MemorySecretStore",
    "MemoryAttemptRecorder",
    "ModelCapability",
    "PydanticModelFactory",
    "ProviderAdapter",
    "ProviderInvocationError",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderUsage",
    "PublicModelCapability",
    "ResolvedModelCapability",
    "SecretBackend",
    "SecretController",
    "SecretReader",
    "SecretReference",
    "SecretStoreConfigurationError",
    "SecretStoreError",
    "SecretStoreOperationError",
    "SecretStorePorts",
    "SecretStoreSettings",
    "SecretWrite",
    "SecretWriter",
    "SafeDecisionSummary",
    "STRATEGY_CATALOG_VERSION_V1",
    "StrategyArchetype",
    "StrategyPreset",
    "TencentSecretController",
    "TencentSecretReader",
    "TencentSecretWriter",
    "TencentSsmSettings",
    "ThinkingEffortPolicy",
    "ThinkingMode",
    "WorkerSecret",
    "build_secret_store_ports",
    "official_strategy_archetype",
    "render_strategy_revision",
    "strategy_preset",
    "tencent_sdk_is_importable",
]
