"""Hosted Arena Agent runtime foundations.

This package exposes the safe capability/Secret Store ports and the
network-free Phase 3 execution foundation. The included Provider is a
deterministic test fake; production Tencent SSM, a real HTTPS Provider adapter,
and a durable Hosted Worker are intentionally not represented as complete.
"""

from .capabilities import (
    CAPABILITY_SCHEMA_VERSION_V1,
    DEFAULT_REGISTRY_VERSION_V1,
    CapabilityError,
    CapabilityRegistry,
    ModelCapability,
    PublicModelCapability,
    ResolvedModelCapability,
    ThinkingEffortPolicy,
    ThinkingMode,
)
from .direct_model_driver import (
    AttemptCompletion,
    AttemptCreated,
    AttemptRecord,
    AttemptRecorder,
    DirectModelConfig,
    DirectModelDriver,
    DirectModelInfrastructureError,
    MemoryAttemptRecorder,
)
from .prompt_builder import (
    BuiltPrompt,
    PromptBuildError,
    PromptBuilder,
)
from .providers import (
    FakeProvider,
    FakeProviderScenario,
    FakeProviderStep,
    ProviderAdapter,
    ProviderInvocationError,
    ProviderRequest,
    ProviderResponse,
    ProviderUsage,
)
from .secret_store import (
    DeploymentEnvironment,
    MemorySecretStore,
    SecretBackend,
    SecretController,
    SecretReader,
    SecretReference,
    SecretStoreConfigurationError,
    SecretStoreError,
    SecretStoreOperationError,
    SecretStorePorts,
    SecretStoreSettings,
    SecretWrite,
    SecretWriter,
    TencentSecretController,
    TencentSecretReader,
    TencentSecretWriter,
    TencentSsmSettings,
    WorkerSecret,
    build_secret_store_ports,
    tencent_sdk_is_importable,
)

__all__ = [
    "CAPABILITY_SCHEMA_VERSION_V1",
    "DEFAULT_REGISTRY_VERSION_V1",
    "AttemptCompletion",
    "AttemptCreated",
    "AttemptRecord",
    "AttemptRecorder",
    "BuiltPrompt",
    "CapabilityError",
    "CapabilityRegistry",
    "DeploymentEnvironment",
    "DirectModelConfig",
    "DirectModelDriver",
    "DirectModelInfrastructureError",
    "FakeProvider",
    "FakeProviderScenario",
    "FakeProviderStep",
    "MemorySecretStore",
    "MemoryAttemptRecorder",
    "ModelCapability",
    "PromptBuildError",
    "PromptBuilder",
    "ProviderAdapter",
    "ProviderInvocationError",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderUsage",
    "PublicModelCapability",
    "ResolvedModelCapability",
    "SecretBackend",
    "SecretController",
    "SecretReader",
    "SecretReference",
    "SecretStoreConfigurationError",
    "SecretStoreError",
    "SecretStoreOperationError",
    "SecretStorePorts",
    "SecretStoreSettings",
    "SecretWrite",
    "SecretWriter",
    "TencentSecretController",
    "TencentSecretReader",
    "TencentSecretWriter",
    "TencentSsmSettings",
    "ThinkingEffortPolicy",
    "ThinkingMode",
    "WorkerSecret",
    "build_secret_store_ports",
    "tencent_sdk_is_importable",
]
